from typing import Final

# Patterns are matched via fnmatch against (a) the absolute normalised path
# and (b) the basename. fnmatch is anchored to the whole string, so to skip
# files inside a directory `X` in an absolute path, use `*/X/*`. To skip the
# directory entry itself in an `ls`, use the bare `X` (basename match).
_IGNORE_DEFAULTS: Final[list[str]] = [
    # ── VCS metadata ─────────────────────────────────────────────────────
    ".git",
    "*/.git/*",
    ".hg",
    "*/.hg/*",
    ".svn",
    "*/.svn/*",
    ".bzr",
    "*/.bzr/*",
    "_darcs",
    "*/_darcs/*",
    # ── Project-local ────────────────────────────────────────────────────
    ".contractor",
    "*/.contractor/*",
    # ── Python ───────────────────────────────────────────────────────────
    "__pycache__",
    "*/__pycache__/*",
    ".venv",
    "*/.venv/*",
    "venv",
    "*/venv/*",
    ".tox",
    "*/.tox/*",
    ".nox",
    "*/.nox/*",
    ".mypy_cache",
    "*/.mypy_cache/*",
    ".pytest_cache",
    "*/.pytest_cache/*",
    ".ruff_cache",
    "*/.ruff_cache/*",
    ".pytype",
    "*/.pytype/*",
    ".pyre",
    "*/.pyre/*",
    ".eggs",
    "*/.eggs/*",
    "*.egg-info",
    "*/*.egg-info/*",
    "__pypackages__",
    "*/__pypackages__/*",
    "htmlcov",
    "*/htmlcov/*",
    ".coverage",
    ".coverage.*",
    "coverage.xml",
    "*.pyc",
    "*.pyo",
    "*.pyd",
    "*.whl",
    # ── JS / TS / web ────────────────────────────────────────────────────
    "node_modules",
    "*/node_modules/*",
    "bower_components",
    "*/bower_components/*",
    ".next",
    "*/.next/*",
    ".nuxt",
    "*/.nuxt/*",
    ".svelte-kit",
    "*/.svelte-kit/*",
    ".cache",
    "*/.cache/*",
    ".parcel-cache",
    "*/.parcel-cache/*",
    ".turbo",
    "*/.turbo/*",
    ".expo",
    "*/.expo/*",
    ".angular",
    "*/.angular/*",
    "*.tsbuildinfo",
    # ── JVM (Java / Kotlin / Scala) ──────────────────────────────────────
    "target",
    "*/target/*",
    "build",
    "*/build/*",
    ".gradle",
    "*/.gradle/*",
    "*.class",
    "*.jar",
    "*.war",
    "*.ear",
    # ── .NET / C# ────────────────────────────────────────────────────────
    "bin",
    "*/bin/*",
    "obj",
    "*/obj/*",
    "Debug",
    "*/Debug/*",
    "Release",
    "*/Release/*",
    # ── C / C++ / CMake ──────────────────────────────────────────────────
    "cmake-build-*",
    "*/cmake-build-*/*",
    "*.o",
    "*.obj",
    "*.a",
    "*.lib",
    "*.so",
    "*.so.*",
    "*.dll",
    "*.dylib",
    "*.pdb",
    # ── Go ───────────────────────────────────────────────────────────────
    "vendor",
    "*/vendor/*",
    # ── Rust uses target/, covered above ────────────────────────────────
    # ── Apple / Swift ────────────────────────────────────────────────────
    "DerivedData",
    "*/DerivedData/*",
    "Pods",
    "*/Pods/*",
    ".build",
    "*/.build/*",
    # ── Generic build / dist ─────────────────────────────────────────────
    "dist",
    "*/dist/*",
    "out",
    "*/out/*",
    "coverage",
    "*/coverage/*",
    # ── IDEs & editors ───────────────────────────────────────────────────
    ".idea",
    "*/.idea/*",
    ".vscode",
    "*/.vscode/*",
    ".vs",
    "*/.vs/*",
    "*.swp",
    "*.swo",
    "*~",
    ".#*",
    # ── Executables & binaries ───────────────────────────────────────────
    "*.exe",
    "*.app",
    "*.bin",
    # ── Images ───────────────────────────────────────────────────────────
    "*.jpg",
    "*.jpeg",
    "*.png",
    "*.gif",
    "*.bmp",
    "*.tiff",
    "*.tif",
    "*.webp",
    "*.svg",
    "*.ico",
    "*.icns",
    "*.heic",
    "*.heif",
    "*.avif",
    "*.psd",
    "*.ai",
    "*.eps",
    # ── Audio / video ────────────────────────────────────────────────────
    "*.mov",
    "*.mp4",
    "*.mkv",
    "*.avi",
    "*.webm",
    "*.flv",
    "*.wmv",
    "*.mpg",
    "*.mpeg",
    "*.m4v",
    "*.mp3",
    "*.wav",
    "*.flac",
    "*.ogg",
    "*.aac",
    "*.m4a",
    "*.opus",
    "*.aiff",
    # ── Archives & disk images ───────────────────────────────────────────
    "*.zip",
    "*.tar",
    "*.tar.gz",
    "*.tgz",
    "*.gz",
    "*.bz2",
    "*.xz",
    "*.7z",
    "*.rar",
    "*.lz",
    "*.lz4",
    "*.zst",
    "*.iso",
    "*.dmg",
    "*.pkg",
    "*.deb",
    "*.rpm",
    # ── Fonts ────────────────────────────────────────────────────────────
    "*.woff",
    "*.woff2",
    "*.ttf",
    "*.otf",
    "*.eot",
    # ── Binary documents ─────────────────────────────────────────────────
    "*.pdf",
    "*.doc",
    "*.docx",
    "*.xls",
    "*.xlsx",
    "*.ppt",
    "*.pptx",
    "*.odt",
    "*.ods",
    "*.odp",
    # ── OS-specific cruft ────────────────────────────────────────────────
    ".DS_Store",
    "*/.DS_Store",
    "Thumbs.db",
    "desktop.ini",
]

INCORRECT_REGEXP_ERROR: Final[str] = "regex {regex} is incorrect:\n{err}"
PATH_NOT_FOUND_ERROR: Final[str] = "path {path} does not exist"
PATH_IS_NOT_A_FILE_ERROR: Final[str] = "{path} is not a file"

FS_COVERAGE_STATE_KEY: Final[str] = "fs_coverage"
