package public

import "net/http"

func (h *handler) registerAuditRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /v1/audit-profiles", h.listAuditProfiles)
	mux.HandleFunc("GET /v1/audit-profiles/{name}/versions/{version}", h.getAuditProfile)
	mux.HandleFunc("GET /v1/audit-standards", h.listAuditStandards)
	mux.HandleFunc("GET /v1/audit-standards/{scheme}/versions/{version}", h.getAuditStandard)
	mux.HandleFunc("POST /v1/projects/{projectId}/audits", h.createAudit)
	mux.HandleFunc("GET /v1/projects/{projectId}/audits", h.listProjectAudits)
	mux.HandleFunc("GET /v1/audits/{auditId}", h.getAudit)
	mux.HandleFunc("POST /v1/audits/{auditId}/start", h.startAudit)
	mux.HandleFunc("POST /v1/audits/{auditId}/pause", h.pauseAudit)
	mux.HandleFunc("POST /v1/audits/{auditId}/resume", h.resumeAudit)
	mux.HandleFunc("POST /v1/audits/{auditId}/cancel", h.cancelAudit)
	mux.HandleFunc("DELETE /v1/audits/{auditId}", h.deleteAudit)
	mux.HandleFunc("GET /v1/audits/{auditId}/items", h.listAuditItems)
	mux.HandleFunc("GET /v1/audits/{auditId}/coverage", h.listAuditCoverage)
	mux.HandleFunc("GET /v1/audits/{auditId}/workspace", h.getAuditWorkspace)
	mux.HandleFunc("GET /v1/audits/{auditId}/reviews/{requestId}", h.getAuditReview)
	mux.HandleFunc("GET /v1/audits/{auditId}/report", h.getAuditReport)
	mux.HandleFunc("GET /v1/audits/{auditId}/finding-proposals", h.listAuditFindingProposals)
	mux.HandleFunc("POST /v1/audits/{auditId}/finding-proposal-imports", h.importAuditFindingProposal)
	mux.HandleFunc("POST /v1/finding-collections", h.publishFindingCollection)
	mux.HandleFunc("GET /v1/audits/{auditId}/findings", h.listAuditFindings)
	mux.HandleFunc("GET /v1/audits/{auditId}/findings/{findingId}", h.getAuditFinding)
	mux.HandleFunc("GET /v1/audits/{auditId}/findings/{findingId}/provenance", h.listAuditFindingProvenance)
	mux.HandleFunc("POST /v1/audits/{auditId}/findings/{findingId}/reviews", h.createAuditFindingReview)
	mux.HandleFunc("GET /v1/audits/{auditId}/reviews", h.listAuditReviews)
	mux.HandleFunc("POST /v1/audits/{auditId}/reviews/{requestId}/decisions", h.decideAuditReview)
	mux.HandleFunc("/v1/audit-profiles/{name}/versions/{version}", h.methodNotAllowed)
	mux.HandleFunc("/v1/audit-profiles", h.methodNotAllowed)
	mux.HandleFunc("/v1/projects/{projectId}/audits", h.methodNotAllowed)
	mux.HandleFunc("/v1/audits/{auditId}/start", h.methodNotAllowed)
	mux.HandleFunc("/v1/audits/{auditId}/items", h.methodNotAllowed)
	mux.HandleFunc("/v1/audits/{auditId}/coverage", h.methodNotAllowed)
	mux.HandleFunc("/v1/audits/{auditId}/workspace", h.methodNotAllowed)
	mux.HandleFunc("/v1/audits/{auditId}/reviews/{requestId}", h.methodNotAllowed)
	mux.HandleFunc("/v1/audits/{auditId}/report", h.methodNotAllowed)
	mux.HandleFunc("/v1/audits/{auditId}/finding-proposals", h.methodNotAllowed)
	mux.HandleFunc("/v1/audits/{auditId}/finding-proposal-imports", h.methodNotAllowed)
	mux.HandleFunc("/v1/finding-collections", h.methodNotAllowed)
	mux.HandleFunc("/v1/audits/{auditId}/findings/{findingId}/provenance", h.methodNotAllowed)
	mux.HandleFunc("/v1/audits/{auditId}/findings/{findingId}/reviews", h.methodNotAllowed)
	mux.HandleFunc("/v1/audits/{auditId}/findings/{findingId}", h.methodNotAllowed)
	mux.HandleFunc("/v1/audits/{auditId}/findings", h.methodNotAllowed)
	mux.HandleFunc("/v1/audits/{auditId}/reviews/{requestId}/decisions", h.methodNotAllowed)
	mux.HandleFunc("/v1/audits/{auditId}/reviews", h.methodNotAllowed)
	mux.HandleFunc("/v1/audits/{auditId}", h.methodNotAllowed)
}
