package public

import "net/http"

func (h *handler) registerOperationsRoutes(mux *http.ServeMux) {
	mux.HandleFunc("GET /v1/operations/credentials", h.listCredentials)
	mux.HandleFunc("POST /v1/operations/credentials", h.createCredential)
	mux.HandleFunc("GET /v1/operations/credentials/{credentialId}", h.getCredential)
	mux.HandleFunc("DELETE /v1/operations/credentials/{credentialId}", h.deleteCredential)
	mux.HandleFunc("GET /v1/operations/runtime-configs", h.listRuntimeConfigs)
	mux.HandleFunc("POST /v1/operations/runtime-configs", h.publishRuntimeConfig)
	mux.HandleFunc("GET /v1/operations/runtime-configs/{name}/versions/{version}", h.getRuntimeConfig)
	mux.HandleFunc("GET /v1/operations/runtime-labels", h.listRuntimeLabels)
	mux.HandleFunc("GET /v1/operations/runtime-labels/{label}", h.getRuntimeLabel)
	mux.HandleFunc("PUT /v1/operations/runtime-labels/{label}", h.putRuntimeLabel)
	mux.HandleFunc("DELETE /v1/operations/runtime-labels/{label}", h.deleteRuntimeLabel)
	mux.HandleFunc("GET /v1/operations/runtime-credentials", h.listRuntimeCredentials)
	mux.HandleFunc("POST /v1/operations/runtime-credentials", h.createRuntimeCredential)
	mux.HandleFunc("GET /v1/operations/runtime-credentials/{credentialId}", h.getRuntimeCredential)
	mux.HandleFunc("DELETE /v1/operations/runtime-credentials/{credentialId}", h.deleteRuntimeCredential)
	mux.HandleFunc("GET /v1/operations/runtime-agent-principals", h.listRuntimeAgentPrincipals)
	mux.HandleFunc("GET /v1/operations/runtime-agent-principals/{runtimeAgentId}", h.getRuntimeAgentPrincipal)
	mux.HandleFunc("DELETE /v1/operations/runtime-agent-principals/{runtimeAgentId}", h.deleteRuntimeAgentPrincipal)
	mux.HandleFunc("PUT /v1/operations/runtime-agent-principals/{runtimeAgentId}/labels", h.putRuntimeAgentLabels)
	mux.HandleFunc("GET /v1/operations/snapshot", h.getOperationsSnapshot)
	mux.HandleFunc("GET /v1/operations/performance", h.getPerformance)
	mux.HandleFunc("GET /v1/operations/performance/history", h.getPerformanceHistory)
	mux.HandleFunc("GET /v1/operations/allocation-history", h.listAllocationResourceHistory)
	mux.HandleFunc("GET /v1/operations/runtime-agents", h.listRuntimeAgents)
	mux.HandleFunc("GET /v1/operations/allocations", h.listAllocations)
	mux.HandleFunc("GET /v1/operations/settings/scheduler", h.getSchedulerSettings)
	mux.HandleFunc("PUT /v1/operations/settings/scheduler", h.putSchedulerSettings)
	mux.HandleFunc("/v1/operations/credentials/{credentialId}", h.methodNotAllowed)
	mux.HandleFunc("/v1/operations/credentials", h.methodNotAllowed)
	mux.HandleFunc("/v1/operations/runtime-configs/{name}/versions/{version}", h.methodNotAllowed)
	mux.HandleFunc("/v1/operations/runtime-configs", h.methodNotAllowed)
	mux.HandleFunc("/v1/operations/runtime-labels/{label}", h.methodNotAllowed)
	mux.HandleFunc("/v1/operations/runtime-labels", h.methodNotAllowed)
	mux.HandleFunc("/v1/operations/runtime-credentials/{credentialId}", h.methodNotAllowed)
	mux.HandleFunc("/v1/operations/runtime-credentials", h.methodNotAllowed)
	mux.HandleFunc("/v1/operations/snapshot", h.methodNotAllowed)
	mux.HandleFunc("/v1/operations/performance", h.methodNotAllowed)
	mux.HandleFunc("/v1/operations/performance/history", h.methodNotAllowed)
	mux.HandleFunc("/v1/operations/allocation-history", h.methodNotAllowed)
	mux.HandleFunc("/v1/operations/runtime-agents", h.methodNotAllowed)
	mux.HandleFunc("/v1/operations/allocations", h.methodNotAllowed)
	mux.HandleFunc("/v1/operations/settings/scheduler", h.methodNotAllowed)
}
