from dataclasses import dataclass


@dataclass
class LikeC4Tools:
    name: str

    def load(self): ...
    def save(self): ...

    def list_models(self): ...
    def list_components(self): ...
    def list_views(self): ...
