from dataclasses import dataclass


@dataclass
class LikeC4Tools:
    name: str

    def load(): ...
    def save(): ...

    def list_models(): ...
    def list_components(): ...
    def list_views(): ...
